task:
  matrix:
    - macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
    - container:
        image: gcc:latest
  compile-script: make clean love
  git-script: x="$(git status --porcelain)" && [ -z "$x" ]

